---
title: "me doing gg"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE)
```

#### Install
```{r, eval = FALSE}
devtools::install_github("einarhjorleifsson/ggmisc")
```

#### Libraries

```{r}
library(ggmisc)
library(tidyverse)
```

#### scale_fill_crayola (only function so far)

```{r, crayola}
read_csv("http://data.hafro.is/assmt/2018/cod/smb.csv") %>% 
  gather(key = age, value = oU, -Year, convert = TRUE) %>% 
  rename(year = Year) %>% 
  mutate(yc = year - age) %>% 
  ggplot() +
  geom_col(aes(year, oU, fill = factor(yc))) + 
  scale_fill_crayola() +
  facet_grid(age ~ ., scale = "free_y") +
  theme(legend.position = "none") +
  scale_y_continuous(NULL, NULL) +
  scale_x_continuous(NULL, breaks = seq(1985, 2015, by = 5)) +
  labs(title = "It is the year class, stupid",
       subtitle = "The signal in the data is not age, not year, but yearclass")
```

